#!/bin/sh

[ "$INTERFACE" != "wan" ] && exit 0

case "$ACTION" in
	ifdown)
		logger -t miniupnpd "*  *  *  Интерфейс - WAN - Упал, останавливаю miniupnpd. *  *  *"
		/etc/init.d/miniupnpd stop
		;;
	ifup)
		logger -t miniupnpd "*  *  *  Интерфейс - WAN - Поднялся, запускаю miniupnpd. *  *  *"
		/etc/init.d/miniupnpd restart
		;;
esac