#!/bin/sh

#logger -s "Запуск скрипта добавления маршрутов для WireGuard"

if [ "$ACTION" = "ifup" ] && [ "$DEVICE" = "wg0" ]; then
    while IFS= read -r route; do
        if echo "$route" | grep -qE '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'; then
            # Если это одиночный IP-адрес, используем -host
            route add -host "$route" dev wg0
        else
            # Иначе считаем, что это сеть и используем -net
            route add -net "$route" dev wg0
        fi
    done < /etc/routes_vpn/routes_ip

    INFOROUTE=$(ip route show | wc -l)
    logger -s "*  *  *  *  Маршруты для WireGuard загружены в количестве ${INFOROUTE}  *  *  *  *"
fi
